image: node:latest
stages:
  - install
  - validation
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: validation
  dependencies:
    - install
  script:
    - npm run lint

test:
  stage: validation
  dependencies:
    - install
  script:
    - npm test

prettier:
  stage: validation
  script:
    - npx prettier --write .

build:  
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' # corre só na main branch
      when: on_success
      allow_failure: true
  artifacts:
    paths:
      - out/

deploy:
  stage: deploy
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
      when: on_success
      allow_failure: true
