image: node:latest
stages:
  - install
  - validation
  - build

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: validation
  dependencies:
    - install
  script:
    - npx eslint .

test:
  stage: validation
  dependencies:
    - install
  script:
    - npm test

prettier:
  stage: validation
  script:
    - npm run prettier

build:
  stage: build
  script:
    - npm run build
