version: 2.1


jobs:
  mp1_jobs:
    docker:
      - image: circleci/node:19.0.0

    steps:
      - checkout #git clone alias

      - run:
          name: "npm dependencies"
          command: 
            npm install --save
      


workflows:
  tdw_mp1_circleci:
    jobs:
      - mp1_jobs